algoritmo "meuprimeiro"
// Função :
// Autor :
// Data : 25/11/2024
// Seção de Declarações 
var
valor, valor2, valor3,  divisao: Real
inicio
// Seção de Comandos
escreval ("digite o primeiro valor:")
leia (valor3)
escreval ("digite o segundo valor2:")
leia(valor2)
escreval ("digite o terceiro valor3:")
leia(valor)
divisao <- (valor3/valor2)/valor

    escreval("o resultado ",divisao)
fimalgoritmo
