algoritmo "aula2"
// Função :
// Autor :
// Data : 21/11/2024
// Seção de Declarações 
var
   valor1, valor2, soma: inteiro
inicio
   // Seção de Comandos
   escreval("Digite o primeiro valor: ")
   Leia(valor1)
   escreval("digite o segundo valor: ")
   Leia(valor2)
   soma <- valor1 + valor2
   
   escreval("o resultado da soma entre ", valor1, " e ", valor2," é ", soma)
fimalgoritmo
